import { useNavigate } from "react-router-dom";
import CtaButton from "../components/CtaButton";

const SECTIONS = [
  {
    number: "01",
    title: "What is SamvaadAI?",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="#03b3c3"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <circle cx="12" cy="12" r="10" />
        <line x1="12" y1="16" x2="12" y2="12" />
        <line x1="12" y1="8" x2="12.01" y2="8" />
      </svg>
    ),
    content:
      "SamvaadAI is an AI-powered mock interview platform designed to help individuals practice and improve their interview skills in a structured environment. It simulates realistic interview scenarios using artificial intelligence, enabling users to prepare with confidence. SamvaadAI is intended solely for practice and learning — it is not a substitute for real hiring interviews or professional evaluation.",
  },
  {
    number: "02",
    title: "Purpose",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="#03b3c3"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <circle cx="12" cy="12" r="10" />
        <polyline points="12 6 12 12 16 14" />
      </svg>
    ),
    content:
      "Many students and job seekers lack access to consistent, structured interview practice. SamvaadAI was built to address this gap by providing an accessible tool where users can rehearse answers, receive objective feedback, and identify areas for improvement — all without the pressure of a real interview setting.",
  },
  {
    number: "03",
    title: "What We Do",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="#03b3c3"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <rect x="2" y="3" width="20" height="14" rx="2" ry="2" />
        <line x1="8" y1="21" x2="16" y2="21" />
        <line x1="12" y1="17" x2="12" y2="21" />
      </svg>
    ),
    content: null,
    list: [
      {
        label: "AI-Generated Questions",
        desc: "Interview questions are generated based on the user's resume and selected role, ensuring relevance and depth.",
      },
      {
        label: "Voice-Based Practice",
        desc: "Users respond to questions verbally using their microphone, simulating the flow of a real interview.",
      },
      {
        label: "AI-Driven Evaluation",
        desc: "After the session, responses are analyzed by AI to provide a score along with specific strengths and areas for improvement.",
      },
    ],
  },
  {
    number: "04",
    title: "Responsible Use",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="#03b3c3"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
      </svg>
    ),
    content:
      "SamvaadAI is a learning and preparation tool. The scores and feedback provided are generated by AI and should be treated as guidance rather than definitive assessment. Users are encouraged to combine platform feedback with mentorship, peer review, and continued self-study for well-rounded interview preparation.",
  },
  {
    number: "05",
    title: "Team",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="#03b3c3"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" />
        <circle cx="9" cy="7" r="4" />
        <path d="M23 21v-2a4 4 0 0 0-3-3.87" />
        <path d="M16 3.13a4 4 0 0 1 0 7.75" />
      </svg>
    ),
    content:
      "SamvaadAI was developed as part of a hackathon initiative by a small team of developers and designers committed to building practical tools for education and career readiness. The project reflects our interest in applying AI responsibly to solve real-world preparation challenges.",
  },
];

export default function AboutUs() {
  const navigate = useNavigate();

  return (
    <>
      <style>{`
        .about-wrapper {
          width: 100vw;
          height: 100vh;
          background: #000;
          display: flex;
          flex-direction: column;
          overflow-y: hidden;
        }
        .about-content {
          flex: 1;
          display: flex;
          flex-direction: column;
          align-items: center;
          padding: 0 2rem 4rem;
          overflow-y: auto;
          gap: 3rem;
        }
        .about-sections {
          width: 100%;
          max-width: 620px;
          display: flex;
          flex-direction: column;
          gap: 0;
        }
        .about-section {
          display: flex;
          gap: 1.25rem;
          align-items: flex-start;
          position: relative;
          padding-bottom: 2.4rem;
        }
        .about-section:last-child {
          padding-bottom: 0;
        }
        .about-section-line {
          position: absolute;
          left: 19px;
          top: 44px;
          bottom: 0;
          width: 1px;
          background: rgba(255,255,255,0.06);
        }
        .about-section:last-child .about-section-line {
          display: none;
        }
        @media (max-width: 768px) {
          .about-wrapper {
            height: auto;
            min-height: 100vh;
            overflow-y: auto;
          }
          .about-content {
            padding: 0 1.25rem 3rem;
            gap: 2.5rem;
          }
        }
      `}</style>

      <div className="about-wrapper">
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            padding: "1.2rem 2rem",
            flexShrink: 0,
          }}
        >
          <span
            style={{
              fontFamily: '"Bricolage Grotesque", sans-serif',
              fontSize: "1.6rem",
              fontWeight: 700,
              letterSpacing: "-0.02em",
              color: "#F5F5F5",
              display: "inline-flex",
              alignItems: "center",
              gap: "0.15em",
              cursor: "pointer",
            }}
            onClick={() => navigate("/")}
          >
            Samvaad
            <span style={{ color: "#03b3c3", fontWeight: 800 }}>AI</span>
          </span>
        </div>

        <div
          style={{
            width: "100%",
            height: "1px",
            background: "rgba(255,255,255,0.06)",
            flexShrink: 0,
          }}
        />

        <div className="about-content">
          <div
            style={{
              textAlign: "center",
              marginTop: "2rem",
              maxWidth: "560px",
            }}
          >
            <h1
              style={{
                fontFamily: '"Bricolage Grotesque", sans-serif',
                fontWeight: 800,
                fontSize: "clamp(1.8rem, 4vw, 3rem)",
                lineHeight: 1.1,
                letterSpacing: "-0.035em",
                color: "#F5F5F5",
                margin: 0,
              }}
            >
              About Us
            </h1>
            <p
              style={{
                fontFamily: '"Quicksand", sans-serif',
                fontSize: "clamp(0.92rem, 1.1vw, 1.05rem)",
                color: "rgba(245,245,245,0.42)",
                marginTop: "0.8rem",
                marginBottom: 0,
                fontWeight: 400,
                lineHeight: 1.7,
              }}
            >
              Learn about SamvaadAI — what we do, why we built it, and how we
              approach responsible AI-powered interview preparation.
            </p>
          </div>

          <div className="about-sections">
            {SECTIONS.map((section) => (
              <div key={section.number} className="about-section">
                <div className="about-section-line" />
                <div
                  style={{
                    width: 40,
                    height: 40,
                    borderRadius: "12px",
                    border: "1px solid rgba(255,255,255,0.08)",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    flexShrink: 0,
                  }}
                >
                  {section.icon}
                </div>
                <div style={{ paddingTop: "0.15rem", flex: 1 }}>
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "0.5rem",
                      marginBottom: "0.3rem",
                    }}
                  >
                    <span
                      style={{
                        fontFamily: '"Bricolage Grotesque", sans-serif',
                        fontSize: "0.65rem",
                        fontWeight: 600,
                        letterSpacing: "0.08em",
                        color: "#03b3c3",
                        opacity: 0.6,
                      }}
                    >
                      {section.number}
                    </span>
                    <span
                      style={{
                        fontFamily: '"Bricolage Grotesque", sans-serif',
                        fontSize: "1.05rem",
                        fontWeight: 700,
                        color: "#F5F5F5",
                        letterSpacing: "-0.01em",
                      }}
                    >
                      {section.title}
                    </span>
                  </div>

                  {section.content && (
                    <p
                      style={{
                        fontFamily: '"Quicksand", sans-serif',
                        fontSize: "0.88rem",
                        fontWeight: 400,
                        lineHeight: 1.65,
                        color: "rgba(245,245,245,0.42)",
                        margin: 0,
                      }}
                    >
                      {section.content}
                    </p>
                  )}

                  {section.list && (
                    <div
                      style={{
                        display: "flex",
                        flexDirection: "column",
                        gap: "0.85rem",
                        marginTop: "0.25rem",
                      }}
                    >
                      {section.list.map((item) => (
                        <div key={item.label}>
                          <span
                            style={{
                              fontFamily: '"Bricolage Grotesque", sans-serif',
                              fontSize: "0.85rem",
                              fontWeight: 600,
                              color: "rgba(245,245,245,0.7)",
                              letterSpacing: "-0.005em",
                            }}
                          >
                            {item.label}
                          </span>
                          <p
                            style={{
                              fontFamily: '"Quicksand", sans-serif',
                              fontSize: "0.85rem",
                              fontWeight: 400,
                              lineHeight: 1.6,
                              color: "rgba(245,245,245,0.38)",
                              margin: "0.15rem 0 0 0",
                            }}
                          >
                            {item.desc}
                          </p>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>

          <div
            style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              gap: "0.6rem",
            }}
          >
            <CtaButton
              text="Try a Mock Interview"
              onClick={() => navigate("/pre-interview")}
            />
            <span
              style={{
                fontFamily: '"Quicksand", sans-serif',
                fontSize: "0.72rem",
                color: "rgba(245,245,245,0.22)",
                fontWeight: 400,
                letterSpacing: "0.02em",
              }}
            >
              No signup required
            </span>
          </div>
        </div>
      </div>
    </>
  );
}
